In [9]:

# NumPy Practice Sheet

import numpy as np

# Creating Arrays

a = np.array([1, 2, 3])
print("Array a:", a)

b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
print("Array b:\n", b)

c = np.zeros((3, 4))
print("Zeros:\n", c)

d = np.ones((2, 3, 4), dtype=np.int16)
print("Ones:\n", d)

e = np.arange(10, 25, 5)
print("Arange:", e)

f = np.linspace(0, 2, 9)
print("Linspace:", f)

g = np.full((2, 2), 7)
print("Full:\n", g)

h = np.eye(2)
print("Identity:\n", h)

rand_arr = np.random.random((2, 2))
print("Random:\n", rand_arr)

empty_arr = np.empty((3, 2))
print("Empty:\n", empty_arr)


Array a: [1 2 3]
Array b:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
Arange: [10 15 20]
Linspace: [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
Full:
 [[7 7]
 [7 7]]
Identity:
 [[1. 0.]
 [0. 1.]]
Random:
 [[0.66583157 0.70174109]
 [0.13422071 0.19929421]]
Empty:
 [[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


In [10]:
# Indexing, Slicing, Boolean

print("a[2]:", a[2])
print("b[1, 2]:", b[1, 2])
print("a[0:2]:", a[0:2])
print("b[0:2,1]:", b[0:2, 1])
print("a reversed:", a[::-1])
print("a[a < 2]:", a[a < 2])

a[2]: 3
b[1, 2]: 6.0
a[0:2]: [1 2]
b[0:2,1]: [2. 5.]
a reversed: [3 2 1]
a[a < 2]: [1]


In [11]:
# Arithmetic Operations

print("a + b:\n", np.add(b, a))
print("a - b:\n", np.subtract(a, b))
print("a * b:\n", np.multiply(a, b))
print("a / b:\n", np.divide(a, b))

print("exp(b):\n", np.exp(b))
print("sqrt(b):\n", np.sqrt(b))
print("sin(a):", np.sin(a))
print("cos(b):\n", np.cos(b))
print("log(a):", np.log(a))

a + b:
 [[2.5 4.  6. ]
 [5.  7.  9. ]]
a - b:
 [[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]
a * b:
 [[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]
a / b:
 [[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]
exp(b):
 [[  4.48168907   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
sqrt(b):
 [[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
sin(a): [0.84147098 0.90929743 0.14112001]
cos(b):
 [[ 0.0707372  -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
log(a): [0.         0.69314718 1.09861229]


In [12]:
# Dot product
print("Dot product:\n", b.dot(b.T))


Dot product:
 [[15.25 34.  ]
 [34.   77.  ]]


In [13]:
# Aggregate Functions

print("Sum:", a.sum())
print("Min:", a.min())
print("Max of b (axis=0):", b.max(axis=0))
print("Cumulative sum of b (axis=1):\n", b.cumsum(axis=1))
print("Mean:", a.mean())
print("Median:", np.median(b))
print("Std dev:", np.std(b))



Sum: 6
Min: 1
Max of b (axis=0): [4. 5. 6.]
Cumulative sum of b (axis=1):
 [[ 1.5  3.5  6.5]
 [ 4.   9.  15. ]]
Mean: 2.0
Median: 3.5
Std dev: 1.5920810978785667


In [14]:
# Reshaping / Manipulation

print("Flatten b:", b.ravel())
print("Reshape g:\n", g.reshape(2, -1))

h = np.array([1, 2, 3])
h.resize((2, 3))
print("Resized h:\n", h)



Flatten b: [1.5 2.  3.  4.  5.  6. ]
Reshape g:
 [[7 7]
 [7 7]]
Resized h:
 [[1 2 3]
 [0 0 0]]


In [15]:
# Concatenation
a1 = np.array([1, 2, 3])
d1 = np.array([10, 15, 20])
print("Concatenate:", np.concatenate((a1, d1)))
print("Stack vertically:\n", np.vstack((a1, d1)))
print("Stack horizontally:\n", np.hstack((a1.reshape(-1,1), d1.reshape(-1,1))))



Concatenate: [ 1  2  3 10 15 20]
Stack vertically:
 [[ 1  2  3]
 [10 15 20]]
Stack horizontally:
 [[ 1 10]
 [ 2 15]
 [ 3 20]]


In [16]:
# Splitting
print("HSplit:", np.hsplit(a1, 3))
c1 = np.array([[1.5, 2, 3], [4, 5, 6]])
print("VSplit:\n", np.vsplit(c1, 2))



HSplit: [array([1]), array([2]), array([3])]
VSplit:
 [array([[1.5, 2. , 3. ]]), array([[4., 5., 6.]])]


In [17]:
# Saving & Loading

np.save("my_array.npy", a)
loaded = np.load("my_array.npy")
print("Loaded array:", loaded)

Loaded array: [1 2 3]
